name = "content-store-service"
main = "src/index.js"
compatibility_date = "2024-08-21"

# Environment variables for all environments
[vars]
ENVIRONMENT = "development"
AUTH_SERVICE_URL = "https://auth.tamyla.com"
CORS_ORIGINS = "http://localhost:3000,http://localhost:3001,https://trading.tamyla.com"
MAX_FILE_SIZE = "26214400"  # 25MB in bytes
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm,audio/mpeg,audio/wav"

# Development environment
[env.development]
vars = { ENVIRONMENT = "development" }

# Staging environment  
[env.staging]
name = "content-store-staging"
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
name = "content-store-production"
vars = { ENVIRONMENT = "production" }

# R2 bucket binding (using existing bucket)
[[r2_buckets]]
binding = "CONTENT_BUCKET"
bucket_name = "tamyla-content-store"
preview_bucket_name = "tamyla-content-store"

# D1 database binding for metadata (commented out until configured)
# [[d1_databases]]
# binding = "CONTENT_DB"
# database_name = "content-store-metadata"
# database_id = "placeholder-database-id"
# preview_database_id = "placeholder-preview-database-id"

# KV binding for caching (commented out until configured)
# [[kv_namespaces]]
# binding = "CONTENT_CACHE"
# id = "placeholder-kv-id"
# preview_id = "placeholder-preview-kv-id"

# Analytics binding
[[analytics_engine_datasets]]
binding = "CONTENT_ANALYTICS"

# Compatibility flags
compatibility_flags = ["nodejs_compat"]
